deployment:
  tasks:
    - export DEPLOY_DIR=/home/allevent/public_html/deployed  # Correct path for deployment
    - /bin/bash:
        command: |
          # Step 1: Install Node.js dependencies
          cd /home/allevent/repositories/testing  # Ensure you're in the correct directory
          npm install --production
          
          # Step 2: Build the React application
          npm run build
          
          # Step 3: Copy the build files to the deployment directory
          rsync -av --delete build/ $DEPLOY_DIR/

    - echo "React.js application deployed successfully to $DEPLOY_DIR"
